### ISSUE TITLE
Background colour is ignored when printing the J-Card

### ISSUE THREAD

**Issue by rockwoofstone** [BrendonIrwan/jcard-template#1]
Set the background colour to something other than white, then print the card, and the colour selected is ignored.

**Comment by BrendonIrwan** [comment]
I was not able to replicate the issue myself. Can you check whether this also happens on the [original version](https://gitlab.com/unixispower/jcard-template)?

**Comment by rockwoofstone** [comment]
No - original version works fine. I'm seeing this issue on 2 different Macs (latest Catalina) trying both Chrome and Safari, and also on a Windows 10 (1809) machine (both Chrome and Edge). Interestingly, problem doesn't occur on iOS (iPhone or iPad), using either Chrome or Safari. Have attached a (low-res) video of the issue on the Mac, compared to the original version.
[J-Card Problem.mov.zip](https://github.com/BrendonIrwan/jcard-template/files/4680587/J-Card.Problem.mov.zip)

**Comment by BrendonIrwan** [comment]
Hello. After some twiddling, I was able to reproduce the issue and the [new revision](https://brendonirwan.github.io/jcard-template) should have it fixed. Can you confirm that this is the case? Thanks!

**Comment by rockwoofstone** [comment]
That looks to have solved it - thanks!
