### ISSUE TITLE
The code isn't working on my domain

### ISSUE THREAD

**Issue by degiekes** [BrendonIrwan/jcard-template#2]
Hi,
I uploaded all the files to my domain but it isn't working on my domain. Why is that?
Because i want to use it on my domain in case of your site is down.
My domain is http://muviddl.nl so that you can see that it isn't working.
Regards,
DE SMEDT GUY

**Comment by BrendonIrwan** [comment]
The site must be used in conjunction with Jekyll. Otherwise this is beyond my grasp.
